// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvcApp.Data;

#nullable disable

namespace MyMvcApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250316053548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MyMvcApp.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "ภาษาไทยเพื่ออาชีพ",
                            Credit = 3
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "ภาษาอังกฤษฟัง-พูด 1",
                            Credit = 3
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "หน้าที่พลเมืองและศีลธรรม",
                            Credit = 3
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudentGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupCode = "2/1"
                        },
                        new
                        {
                            Id = 2,
                            GroupCode = "2/2"
                        },
                        new
                        {
                            Id = 3,
                            GroupCode = "2/3"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.Studying", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Term")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("Studyings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Score = 3,
                            StudentId = 1,
                            Term = 1,
                            Year = 2017
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Score = 3,
                            StudentId = 2,
                            Term = 2,
                            Year = 2016
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Score = 4,
                            StudentId = 3,
                            Term = 2,
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Score = 2,
                            StudentId = 4,
                            Term = 2,
                            Year = 2016
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Score = 4,
                            StudentId = 5,
                            Term = 1,
                            Year = 2017
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.Studying", b =>
                {
                    b.HasOne("MyMvcApp.Models.Course", "Course")
                        .WithMany("Studyings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.StudentGroup", null)
                        .WithMany("Studyings")
                        .HasForeignKey("StudentGroupId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MyMvcApp.Models.Course", b =>
                {
                    b.Navigation("Studyings");
                });

            modelBuilder.Entity("MyMvcApp.Models.StudentGroup", b =>
                {
                    b.Navigation("Studyings");
                });
#pragma warning restore 612, 618
        }
    }
}
